package com.itexcelsior.broadcast.video.impl;

import com.itexcelsior.broadcast.common.core.base.BaseApiService;
import com.itexcelsior.broadcast.common.core.base.BaseResponse;
import com.itexcelsior.broadcast.video.manage.VideoFileInfoManager;
import com.itexcelsior.broadcast.video.model.VideoFileInfo;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;
import java.util.Map;

/**
 * @author zxw </br>
 * @create </br>
 * @description: save path & filename of mp4 file generated by SRS server </br>
 */
@RestController
public class VideoServiceImpl extends BaseApiService {

    @Autowired
    private VideoFileInfoManager videoFileInfoManager;


    @GetMapping("/getFileInfo")
    public BaseResponse getFileInfo() {


        return setResultSuccess("查询成功");
    }


    @PostMapping("/onPlay")
    public BaseResponse onPlay(String jsonStr) {
        System.out.println("·····················有人播放了视频············");
        return setResultSuccess("查询成功");
    }

    @PostMapping("/onStop")
    public BaseResponse onStop(String jsonStr) {
        System.out.println("·····················有人停止了视频············");
        return setResultSuccess("查询成功");
    }


    /**
     * json格式:
     * {
     * #           "action": "on_dvr",
     * #           "client_id": 1985,
     * #           "ip": "192.168.1.10", "vhost": "video.test.com", "app": "live",
     * #           "stream": "livestream", "param":"?token=xxx&salt=yyy",
     * #           "cwd": "/usr/local/srs",
     * #           "file": "./objs/nginx/html/live/livestream.1420254068776.flv"
     * #       }
     *
     * @param map
     * @return
     */
    @PostMapping("/onDvr")
    public BaseResponse onDvr(@RequestBody Map map) {
        System.out.println("·····················保存录制文件名称············");

//        JSONObject jsonObject = JSONObject.parseObject(jsonStr);
//        Map<String,Object> map= jsonObject;

        VideoFileInfo videoFileInfo = new VideoFileInfo((String) map.get("ip"),
                (String) map.get("vhost"),
                (String) map.get("app"),
                (String) map.get("stream"),
                (String) map.get("param"),
                (String) map.get("cwd"),
                (String) map.get("file"));

        for (Object entry : map.entrySet()) {
            System.out.println("| --------  key:" + ((Map.Entry) entry).getKey() + ",vale:" + ((Map.Entry) entry).getValue() + " -------- |");
        }


        videoFileInfoManager.add(videoFileInfo);

        return setResultSuccess("查询成功");
    }


    /**
     * 可以添加根据开始时间按天查询
     *
     * @return
     */
    @PostMapping("/findAll")
    public List<VideoFileInfo> findAll() {
        return videoFileInfoManager.findAll();
    }


}
